services:
  mongo:
    image: mongo:7
    container_name: mongodb
    volumes:
      - mongo:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev_pass
    ports:
      - "47015:27017"

volumes:
  mongo: